server:
  port: 8000
  servlet:
    context-path: /desktop

spring:
  application:
    name: shandan-desktop
  profiles:
    active: prod #选择配置分支，先读取系统环境变量，如果没有则默认值为 prod

  #修改thymeleaf访问根路径
  thymeleaf:
    prefix: classpath:/view/

  #mvc接收参数时对日期进行格式化
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss